{{- if .Values.puppetserver.rbac.create }}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ default "puppetserver" .Values.puppetserver.serviceAccount.accountName }}-rb
  namespace: {{ .Release.Namespace }}
  {{- if or (.Values.puppetserver.preGeneratedCertsJob.enabled) (.Values.singleCA.enabled) (.Values.storage.annotations) }}
  annotations:
  {{- end }}
    {{- if or (.Values.puppetserver.preGeneratedCertsJob.enabled) (.Values.singleCA.enabled) }}
    helm.sh/hook: pre-install
    helm.sh/hook-delete-policy: before-hook-creation
    helm.sh/hook-weight: "-10"
    {{- end }}
    {{- if .Values.storage.annotations }}
    {{ toYaml .Values.storage.annotations }}
    {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ default "puppetserver" .Values.puppetserver.serviceAccount.accountName }}-role
subjects:
  - kind: ServiceAccount
    name: {{ default "puppetserver" .Values.puppetserver.serviceAccount.accountName }}
    namespace: {{ .Release.Namespace }}
{{- end }}
